//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the sensor_fusion_core package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __sensor_fusion_core__SENSOR_FUSION_CORECONFIG_H__
#define __sensor_fusion_core__SENSOR_FUSION_CORECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace sensor_fusion_core
{
  class sensor_fusion_coreConfigStatics;
  
  class sensor_fusion_coreConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(sensor_fusion_coreConfig &config, const sensor_fusion_coreConfig &max, const sensor_fusion_coreConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const sensor_fusion_coreConfig &config1, const sensor_fusion_coreConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, sensor_fusion_coreConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const sensor_fusion_coreConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, sensor_fusion_coreConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const sensor_fusion_coreConfig &config) const = 0;
      virtual void getValue(const sensor_fusion_coreConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T sensor_fusion_coreConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (sensor_fusion_coreConfig::* field);

      virtual void clamp(sensor_fusion_coreConfig &config, const sensor_fusion_coreConfig &max, const sensor_fusion_coreConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const sensor_fusion_coreConfig &config1, const sensor_fusion_coreConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, sensor_fusion_coreConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const sensor_fusion_coreConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, sensor_fusion_coreConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const sensor_fusion_coreConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const sensor_fusion_coreConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, sensor_fusion_coreConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, sensor_fusion_coreConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<sensor_fusion_coreConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(sensor_fusion_coreConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("init_filter"==(*_i)->name){init_filter = boost::any_cast<bool>(val);}
        if("scale_init"==(*_i)->name){scale_init = boost::any_cast<double>(val);}
        if("fixed_scale"==(*_i)->name){fixed_scale = boost::any_cast<bool>(val);}
        if("fixed_bias"==(*_i)->name){fixed_bias = boost::any_cast<bool>(val);}
        if("fixed_calib"==(*_i)->name){fixed_calib = boost::any_cast<bool>(val);}
        if("noise_acc"==(*_i)->name){noise_acc = boost::any_cast<double>(val);}
        if("noise_accbias"==(*_i)->name){noise_accbias = boost::any_cast<double>(val);}
        if("noise_gyr"==(*_i)->name){noise_gyr = boost::any_cast<double>(val);}
        if("noise_gyrbias"==(*_i)->name){noise_gyrbias = boost::any_cast<double>(val);}
        if("noise_scale"==(*_i)->name){noise_scale = boost::any_cast<double>(val);}
        if("noise_qwv"==(*_i)->name){noise_qwv = boost::any_cast<double>(val);}
        if("noise_qci"==(*_i)->name){noise_qci = boost::any_cast<double>(val);}
        if("noise_pic"==(*_i)->name){noise_pic = boost::any_cast<double>(val);}
        if("delay"==(*_i)->name){delay = boost::any_cast<double>(val);}
        if("set_height"==(*_i)->name){set_height = boost::any_cast<bool>(val);}
        if("height"==(*_i)->name){height = boost::any_cast<double>(val);}
        if("meas_noise1"==(*_i)->name){meas_noise1 = boost::any_cast<double>(val);}
        if("meas_noise2"==(*_i)->name){meas_noise2 = boost::any_cast<double>(val);}
      }
    }

    bool init_filter;
double scale_init;
bool fixed_scale;
bool fixed_bias;
bool fixed_calib;
double noise_acc;
double noise_accbias;
double noise_gyr;
double noise_gyrbias;
double noise_scale;
double noise_qwv;
double noise_qci;
double noise_pic;
double delay;
bool set_height;
double height;
double meas_noise1;
double meas_noise2;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool init_filter;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double scale_init;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool fixed_scale;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool fixed_bias;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool fixed_calib;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_acc;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_accbias;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_gyr;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_gyrbias;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_scale;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_qwv;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_qci;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noise_pic;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double delay;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool set_height;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double height;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double meas_noise1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double meas_noise2;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("sensor_fusion_coreConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const sensor_fusion_coreConfig &__max__ = __getMax__();
      const sensor_fusion_coreConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const sensor_fusion_coreConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const sensor_fusion_coreConfig &__getDefault__();
    static const sensor_fusion_coreConfig &__getMax__();
    static const sensor_fusion_coreConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const sensor_fusion_coreConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void sensor_fusion_coreConfig::ParamDescription<std::string>::clamp(sensor_fusion_coreConfig &config, const sensor_fusion_coreConfig &max, const sensor_fusion_coreConfig &min) const
  {
    return;
  }

  class sensor_fusion_coreConfigStatics
  {
    friend class sensor_fusion_coreConfig;
    
    sensor_fusion_coreConfigStatics()
    {
sensor_fusion_coreConfig::GroupDescription<sensor_fusion_coreConfig::DEFAULT, sensor_fusion_coreConfig> Default("Default", "", 0, 0, true, &sensor_fusion_coreConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.init_filter = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.init_filter = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.init_filter = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("init_filter", "bool", 1, "call filter init using defined scale", "", &sensor_fusion_coreConfig::init_filter)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("init_filter", "bool", 1, "call filter init using defined scale", "", &sensor_fusion_coreConfig::init_filter)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.scale_init = 0.001;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.scale_init = 30.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.scale_init = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("scale_init", "double", 2, "value for initial scale", "", &sensor_fusion_coreConfig::scale_init)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("scale_init", "double", 2, "value for initial scale", "", &sensor_fusion_coreConfig::scale_init)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fixed_scale = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fixed_scale = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fixed_scale = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_scale", "bool", 2, "fix scale", "", &sensor_fusion_coreConfig::fixed_scale)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_scale", "bool", 2, "fix scale", "", &sensor_fusion_coreConfig::fixed_scale)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fixed_bias = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fixed_bias = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fixed_bias = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_bias", "bool", 2, "fix biases", "", &sensor_fusion_coreConfig::fixed_bias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_bias", "bool", 2, "fix biases", "", &sensor_fusion_coreConfig::fixed_bias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fixed_calib = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fixed_calib = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fixed_calib = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_calib", "bool", 2, "fix calibration states", "", &sensor_fusion_coreConfig::fixed_calib)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("fixed_calib", "bool", 2, "fix calibration states", "", &sensor_fusion_coreConfig::fixed_calib)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_acc = 0.0001;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_acc = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_acc = 0.0083;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_acc", "double", 2, "noise accelerations (std. dev)", "", &sensor_fusion_coreConfig::noise_acc)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_acc", "double", 2, "noise accelerations (std. dev)", "", &sensor_fusion_coreConfig::noise_acc)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_accbias = 1e-07;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_accbias = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_accbias = 0.00083;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_accbias", "double", 2, "noise acceleration bias  (std. dev)", "", &sensor_fusion_coreConfig::noise_accbias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_accbias", "double", 2, "noise acceleration bias  (std. dev)", "", &sensor_fusion_coreConfig::noise_accbias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_gyr = 0.0001;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_gyr = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_gyr = 0.0013;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_gyr", "double", 2, "noise gyros (std. dev)", "", &sensor_fusion_coreConfig::noise_gyr)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_gyr", "double", 2, "noise gyros (std. dev)", "", &sensor_fusion_coreConfig::noise_gyr)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_gyrbias = 1e-07;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_gyrbias = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_gyrbias = 0.00013;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_gyrbias", "double", 2, "noise gyro biases  (std. dev)", "", &sensor_fusion_coreConfig::noise_gyrbias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_gyrbias", "double", 2, "noise gyro biases  (std. dev)", "", &sensor_fusion_coreConfig::noise_gyrbias)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_scale = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_scale = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_scale = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_scale", "double", 2, "noise scale (std. dev)", "", &sensor_fusion_coreConfig::noise_scale)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_scale", "double", 2, "noise scale (std. dev)", "", &sensor_fusion_coreConfig::noise_scale)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_qwv = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_qwv = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_qwv = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_qwv", "double", 2, "noise qwv (std. dev)", "", &sensor_fusion_coreConfig::noise_qwv)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_qwv", "double", 2, "noise qwv (std. dev)", "", &sensor_fusion_coreConfig::noise_qwv)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_qci = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_qci = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_qci = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_qci", "double", 2, "noise qci (std. dev)", "", &sensor_fusion_coreConfig::noise_qci)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_qci", "double", 2, "noise qci (std. dev)", "", &sensor_fusion_coreConfig::noise_qci)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_pic = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_pic = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_pic = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_pic", "double", 2, "noise pic (std. dev)", "", &sensor_fusion_coreConfig::noise_pic)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("noise_pic", "double", 2, "noise pic (std. dev)", "", &sensor_fusion_coreConfig::noise_pic)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.delay = -2.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.delay = 2.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.delay = 0.03;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("delay", "double", 2, "fix delay in seconds", "", &sensor_fusion_coreConfig::delay)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("delay", "double", 2, "fix delay in seconds", "", &sensor_fusion_coreConfig::delay)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.set_height = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.set_height = 1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.set_height = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("set_height", "bool", 4, "call filter init using defined height", "", &sensor_fusion_coreConfig::set_height)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<bool>("set_height", "bool", 4, "call filter init using defined height", "", &sensor_fusion_coreConfig::set_height)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.height = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.height = 20.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.height = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("height", "double", 2, "height in m for init", "", &sensor_fusion_coreConfig::height)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("height", "double", 2, "height in m for init", "", &sensor_fusion_coreConfig::height)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.meas_noise1 = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.meas_noise1 = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.meas_noise1 = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("meas_noise1", "double", 2, "noise for measurement sensor (std. dev)", "", &sensor_fusion_coreConfig::meas_noise1)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("meas_noise1", "double", 2, "noise for measurement sensor (std. dev)", "", &sensor_fusion_coreConfig::meas_noise1)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.meas_noise2 = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.meas_noise2 = 10.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.meas_noise2 = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("meas_noise2", "double", 2, "noise for measurement sensor (std. dev)", "", &sensor_fusion_coreConfig::meas_noise2)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr(new sensor_fusion_coreConfig::ParamDescription<double>("meas_noise2", "double", 2, "noise for measurement sensor (std. dev)", "", &sensor_fusion_coreConfig::meas_noise2)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(sensor_fusion_coreConfig::AbstractGroupDescriptionConstPtr(new sensor_fusion_coreConfig::GroupDescription<sensor_fusion_coreConfig::DEFAULT, sensor_fusion_coreConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<sensor_fusion_coreConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<sensor_fusion_coreConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    sensor_fusion_coreConfig __max__;
    sensor_fusion_coreConfig __min__;
    sensor_fusion_coreConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const sensor_fusion_coreConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static sensor_fusion_coreConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &sensor_fusion_coreConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const sensor_fusion_coreConfig &sensor_fusion_coreConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const sensor_fusion_coreConfig &sensor_fusion_coreConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const sensor_fusion_coreConfig &sensor_fusion_coreConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<sensor_fusion_coreConfig::AbstractParamDescriptionConstPtr> &sensor_fusion_coreConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<sensor_fusion_coreConfig::AbstractGroupDescriptionConstPtr> &sensor_fusion_coreConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const sensor_fusion_coreConfigStatics *sensor_fusion_coreConfig::__get_statics__()
  {
    const static sensor_fusion_coreConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = sensor_fusion_coreConfigStatics::get_instance();
    
    return statics;
  }

//#line 41 "/home/aicrobo/basic_algo/src/sensor_fusion/sensor_fusion_core/cfg/sensor_fusion_core.cfg"
      const int sensor_fusion_core_INIT_FILTER = 1;
//#line 42 "/home/aicrobo/basic_algo/src/sensor_fusion/sensor_fusion_core/cfg/sensor_fusion_core.cfg"
      const int sensor_fusion_core_MISC = 2;
//#line 43 "/home/aicrobo/basic_algo/src/sensor_fusion/sensor_fusion_core/cfg/sensor_fusion_core.cfg"
      const int sensor_fusion_core_SET_HEIGHT = 4;
}

#endif // __SENSOR_FUSION_CORERECONFIGURATOR_H__
